name: CI/CD Pipeline

on:
  pull_request:
    branches:
    - main


jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: minwolf999/social-network:latest

    steps:
      -name: Checkout code
      uses: actions/checkout@v3

      -name: GO Test
      uses: ./Backend/script.sh

      